/**
 * Generate src/executor/abi/{DeskLane,DeskLaneFactory,PriceFence}.ts from the FROZEN interface ABIs
 * in contracts/abi/*.json (snapshotted from contracts/out).
 *
 *     pnpm abi:sync            write the modules
 *     pnpm abi:sync --check    exit 1 if the committed modules are out of date
 *
 * The agent's ABI is deliberately SMALLER than the contract's: every owner-only, admin and
 * config-changing function is stripped, so withdraw / unpause / setCaps / proposeOperator / … are
 * unrepresentable in the agent (viem cannot encode a function the ABI does not contain). Every
 * function of the source ABI must be classified below; an unknown one fails generation, so an
 * interface change forces a conscious decision here.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { type Abi, type AbiFunction, toFunctionSelector, toFunctionSignature } from "viem";

const HERE = dirname(fileURLToPath(import.meta.url));
export const AGENT_ROOT = resolve(HERE, "..");
export const CONTRACTS_ABI_DIR = resolve(AGENT_ROOT, "..", "contracts", "abi");
export const OUT_DIR = resolve(AGENT_ROOT, "src", "executor", "abi");

/** The operator's entire write surface. Nothing else is ever encoded by the agent. */
export const OPERATOR_FUNCTIONS = [
  "rerange",
  "reduce",
  "collect",
  "exitAll",
  "signal",
  "pause",
] as const;

/** Mutating lane functions the agent must never be able to encode (owner, factory, config). */
export const FORBIDDEN_LANE_FUNCTIONS = [
  "initialize",
  "unpause",
  "withdraw",
  "withdrawAll",
  "withdrawPosition",
  "proposeOperator",
  "applyOperator",
  "revokeOperator",
  "setCaps",
  "applyCaps",
  "cancelCaps",
  "setGuardian",
  "setClosedUntil",
] as const;

/** Mutating factory functions (permissionless createLane and admin): the agent reads, never writes. */
export const FORBIDDEN_FACTORY_FUNCTIONS = [
  "createLane",
  "setImplementation",
  "setPoolAllowed",
  "setCeilings",
  "proposeAdmin",
  "acceptAdmin",
] as const;

type AbiItem = Abi[number];

function isView(f: AbiFunction): boolean {
  return f.stateMutability === "view" || f.stateMutability === "pure";
}

/** Keep events, errors, views and the allowed writes; throw on anything unclassified. */
export function filterAbi(
  abi: Abi,
  allowedWrites: readonly string[],
  forbidden: readonly string[],
  label: string,
): Abi {
  const out: AbiItem[] = [];
  for (const item of abi) {
    if (item.type !== "function") {
      out.push(item);
      continue;
    }
    if (isView(item)) {
      out.push(item);
    } else if (allowedWrites.includes(item.name)) {
      out.push(item);
    } else if (!forbidden.includes(item.name)) {
      throw new Error(
        `${label}: mutating function "${item.name}" is neither an operator function nor forbidden; classify it in scripts/abi-sync.ts`,
      );
    }
  }
  return out;
}

export function operatorSelectors(
  abi: Abi,
): Record<(typeof OPERATOR_FUNCTIONS)[number], `0x${string}`> {
  const out: Partial<Record<(typeof OPERATOR_FUNCTIONS)[number], `0x${string}`>> = {};
  for (const name of OPERATOR_FUNCTIONS) {
    const fns = abi.filter((i): i is AbiFunction => i.type === "function" && i.name === name);
    if (fns.length !== 1)
      throw new Error(`expected exactly one "${name}" in the lane ABI, found ${fns.length}`);
    out[name] = toFunctionSelector(fns[0] as AbiFunction);
  }
  return out as Record<(typeof OPERATOR_FUNCTIONS)[number], `0x${string}`>;
}

function header(source: string): string {
  return [
    "// GENERATED by scripts/abi-sync.ts from contracts/abi/" +
      source +
      ". DO NOT EDIT: run `pnpm abi:sync`.",
    "// Owner-only, admin and config-changing functions are stripped on purpose (unrepresentable in the agent).",
    "",
  ].join("\n");
}

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export interface GeneratedModules {
  "DeskLane.ts": string;
  "DeskLaneFactory.ts": string;
  "PriceFence.ts": string;
}

export function readSourceAbi(name: string, dir: string = CONTRACTS_ABI_DIR): Abi {
  return JSON.parse(readFileSync(join(dir, `${name}.json`), "utf8")) as Abi;
}

export function renderModules(dir: string = CONTRACTS_ABI_DIR): GeneratedModules {
  const laneFull = readSourceAbi("IDeskLane", dir);
  const factoryFull = readSourceAbi("IDeskLaneFactory", dir);
  const fence = readSourceAbi("IPriceFence", dir);

  const lane = filterAbi(laneFull, OPERATOR_FUNCTIONS, FORBIDDEN_LANE_FUNCTIONS, "IDeskLane");
  const factory = filterAbi(factoryFull, [], FORBIDDEN_FACTORY_FUNCTIONS, "IDeskLaneFactory");
  const fenceAbi = filterAbi(fence, [], [], "IPriceFence");
  const selectors = operatorSelectors(lane);
  const signatures = Object.fromEntries(
    OPERATOR_FUNCTIONS.map((n) => [
      n,
      toFunctionSignature(lane.find((i) => i.type === "function" && i.name === n) as AbiFunction),
    ]),
  );

  const deskLane = [
    header("IDeskLane.json"),
    `export const deskLaneAbi = ${literal(lane)} as const;`,
    "",
    "/** The operator's entire write surface: rerange, reduce, collect, exitAll, signal, pause. */",
    `export const OPERATOR_SELECTORS = ${literal(selectors)} as const;`,
    "",
    `export const OPERATOR_SIGNATURES = ${literal(signatures)} as const;`,
    "",
    "export type OperatorFunction = keyof typeof OPERATOR_SELECTORS;",
    "",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emits a TypeScript template-literal type into the generated module
    "export const OPERATOR_SELECTOR_SET: ReadonlySet<`0x${string}`> = new Set(Object.values(OPERATOR_SELECTORS));",
    "",
  ].join("\n");

  const deskLaneFactory = [
    header("IDeskLaneFactory.json"),
    `export const deskLaneFactoryAbi = ${literal(factory)} as const;`,
    "",
  ].join("\n");
  const priceFence = [
    header("IPriceFence.json"),
    `export const priceFenceAbi = ${literal(fenceAbi)} as const;`,
    "",
  ].join("\n");

  return {
    "DeskLane.ts": deskLane,
    "DeskLaneFactory.ts": deskLaneFactory,
    "PriceFence.ts": priceFence,
  };
}

function main(): void {
  const check = process.argv.includes("--check");
  const modules = renderModules();
  let stale = 0;
  for (const [file, content] of Object.entries(modules)) {
    const path = join(OUT_DIR, file);
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing */
    }
    if (current === content) continue;
    if (check) {
      console.error(`stale: ${path}`);
      stale += 1;
    } else {
      writeFileSync(path, content);
      console.log(`wrote ${path}`);
    }
  }
  if (check && stale > 0) {
    console.error("ABI modules are out of date: run `pnpm abi:sync`.");
    process.exit(1);
  }
  if (!check) console.log("abi-sync: up to date");
}

const isMain =
  typeof process.argv[1] === "string" && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
