/**
 * Generate src/executor/abi/{DeskLane,DeskLaneFactory,PriceFence}.ts from the FROZEN interface ABIs
 * in contracts/abi/I*.json plus the implementation-only items in contracts/abi/extras.json (both
 * snapshotted from contracts/out; extras by contracts/scripts/abi-extras.py).
 *
 *     pnpm abi:sync            write the modules
 *     pnpm abi:sync --check    exit 1 if the committed modules are out of date (extras included)
 *
 * The agent's ABI is deliberately SMALLER than the contract's: every owner-only, admin and
 * config-changing function is stripped, so withdraw / unpause / setCaps / proposeOperator /
 * applyImplementation / … are unrepresentable in the agent (viem cannot encode a function the ABI
 * does not contain). Every function of the source ABIs, extras included, must be classified below;
 * an unknown one fails generation, so an interface or implementation change forces a conscious
 * decision here.
 *
 * extras.json brings the implementation's custom errors (ReentrancyGuardReentrantCall,
 * SafeERC20FailedOperation, the factory's LaneExists / ImplementationTimelocked / …, the fence's
 * BadConfig) so every revert decodes by name, and read-side items (views, events such as the
 * factory's listed / LaneListed / pendingImplementation / ImplementationProposed). An extras item
 * may not redefine a frozen one, and an unknown extras section fails generation.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { type Abi, type AbiFunction, toFunctionSelector, toFunctionSignature } from "viem";

const HERE = dirname(fileURLToPath(import.meta.url));
export const AGENT_ROOT = resolve(HERE, "..");
export const CONTRACTS_ABI_DIR = resolve(AGENT_ROOT, "..", "contracts", "abi");
export const OUT_DIR = resolve(AGENT_ROOT, "src", "executor", "abi");

/** The operator's entire write surface. Nothing else is ever encoded by the agent. */
export const OPERATOR_FUNCTIONS = [
  "rerange",
  "reduce",
  "collect",
  "exitAll",
  "signal",
  "pause",
] as const;

/** Mutating lane functions the agent must never be able to encode (owner, factory, config). */
export const FORBIDDEN_LANE_FUNCTIONS = [
  "initialize",
  "unpause",
  "withdraw",
  "withdrawAll",
  "withdrawPosition",
  "proposeOperator",
  "applyOperator",
  "revokeOperator",
  "setCaps",
  "applyCaps",
  "cancelCaps",
  "setGuardian",
  "setClosedUntil",
] as const;

/** Mutating factory functions (permissionless createLane and admin): the agent reads, never writes. */
export const FORBIDDEN_FACTORY_FUNCTIONS = [
  "createLane",
  "setImplementation",
  "applyImplementation",
  "setPoolAllowed",
  "setCeilings",
  "proposeAdmin",
  "acceptAdmin",
] as const;

/** The sections of contracts/abi/extras.json, by the module each one extends. */
export const EXTRAS_SECTIONS = ["lane", "factory", "fence"] as const;
export type ExtrasSection = (typeof EXTRAS_SECTIONS)[number];
export type AbiExtras = Record<ExtrasSection, Abi>;

type AbiItem = Abi[number];

function isView(f: AbiFunction): boolean {
  return f.stateMutability === "view" || f.stateMutability === "pure";
}

/** Keep events, errors, views and the allowed writes; throw on anything unclassified. */
export function filterAbi(
  abi: Abi,
  allowedWrites: readonly string[],
  forbidden: readonly string[],
  label: string,
): Abi {
  const out: AbiItem[] = [];
  for (const item of abi) {
    if (item.type !== "function") {
      out.push(item);
      continue;
    }
    if (isView(item)) {
      out.push(item);
    } else if (allowedWrites.includes(item.name)) {
      out.push(item);
    } else if (!forbidden.includes(item.name)) {
      throw new Error(
        `${label}: mutating function "${item.name}" is neither an operator function nor forbidden; classify it in scripts/abi-sync.ts`,
      );
    }
  }
  return out;
}

export function operatorSelectors(
  abi: Abi,
): Record<(typeof OPERATOR_FUNCTIONS)[number], `0x${string}`> {
  const out: Partial<Record<(typeof OPERATOR_FUNCTIONS)[number], `0x${string}`>> = {};
  for (const name of OPERATOR_FUNCTIONS) {
    const fns = abi.filter((i): i is AbiFunction => i.type === "function" && i.name === name);
    if (fns.length !== 1)
      throw new Error(`expected exactly one "${name}" in the lane ABI, found ${fns.length}`);
    out[name] = toFunctionSelector(fns[0] as AbiFunction);
  }
  return out as Record<(typeof OPERATOR_FUNCTIONS)[number], `0x${string}`>;
}

function header(source: string, section: ExtrasSection): string {
  return [
    `// GENERATED by scripts/abi-sync.ts from contracts/abi/${source} + extras.json#${section}. DO NOT EDIT: run \`pnpm abi:sync\`.`,
    "// Owner-only, admin and config-changing functions are stripped on purpose (unrepresentable in the agent).",
    "",
  ].join("\n");
}

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export interface GeneratedModules {
  "DeskLane.ts": string;
  "DeskLaneFactory.ts": string;
  "PriceFence.ts": string;
}

export function readSourceAbi(name: string, dir: string = CONTRACTS_ABI_DIR): Abi {
  return JSON.parse(readFileSync(join(dir, `${name}.json`), "utf8")) as Abi;
}

/** contracts/abi/extras.json, validated: exactly the known sections (plus `generated_by`), each an ABI. */
export function readExtras(dir: string = CONTRACTS_ABI_DIR): AbiExtras {
  const raw = JSON.parse(readFileSync(join(dir, "extras.json"), "utf8")) as Record<string, unknown>;
  for (const key of Object.keys(raw)) {
    if (key !== "generated_by" && !(EXTRAS_SECTIONS as readonly string[]).includes(key))
      throw new Error(`extras.json: unknown section "${key}"; classify it in scripts/abi-sync.ts`);
  }
  const out: Partial<AbiExtras> = {};
  for (const key of EXTRAS_SECTIONS) {
    const items = raw[key];
    if (!Array.isArray(items)) throw new Error(`extras.json: section "${key}" is missing`);
    out[key] = items as Abi;
  }
  return out as AbiExtras;
}

/** type + name + input types: the identity of an ABI item (overloads differ by inputs). */
function itemKey(item: AbiItem): string {
  const name = "name" in item ? item.name : "";
  const inputs = "inputs" in item ? item.inputs.map((i) => i.type).join(",") : "";
  return `${item.type}:${name}(${inputs})`;
}

/**
 * The frozen interface plus the implementation-only extras. An exact duplicate is dropped; an
 * extras item that redefines a frozen one (same key, different outputs or mutability) fails.
 */
export function mergeExtras(frozen: Abi, extras: Abi, label: string): Abi {
  const seen = new Map(frozen.map((i) => [itemKey(i), JSON.stringify(i)]));
  const out: AbiItem[] = [...frozen];
  for (const item of extras) {
    const key = itemKey(item);
    const prior = seen.get(key);
    if (prior !== undefined) {
      if (prior !== JSON.stringify(item))
        throw new Error(`${label}: extras.json redefines the frozen ${key}`);
      continue;
    }
    seen.set(key, JSON.stringify(item));
    out.push(item);
  }
  return out;
}

export function renderModules(dir: string = CONTRACTS_ABI_DIR): GeneratedModules {
  const extras = readExtras(dir);
  const laneFull = mergeExtras(readSourceAbi("IDeskLane", dir), extras.lane, "IDeskLane");
  const factoryFull = mergeExtras(
    readSourceAbi("IDeskLaneFactory", dir),
    extras.factory,
    "IDeskLaneFactory",
  );
  const fence = mergeExtras(readSourceAbi("IPriceFence", dir), extras.fence, "IPriceFence");

  const lane = filterAbi(laneFull, OPERATOR_FUNCTIONS, FORBIDDEN_LANE_FUNCTIONS, "IDeskLane");
  const factory = filterAbi(factoryFull, [], FORBIDDEN_FACTORY_FUNCTIONS, "IDeskLaneFactory");
  const fenceAbi = filterAbi(fence, [], [], "IPriceFence");
  const selectors = operatorSelectors(lane);
  const signatures = Object.fromEntries(
    OPERATOR_FUNCTIONS.map((n) => [
      n,
      toFunctionSignature(lane.find((i) => i.type === "function" && i.name === n) as AbiFunction),
    ]),
  );

  const deskLane = [
    header("IDeskLane.json", "lane"),
    `export const deskLaneAbi = ${literal(lane)} as const;`,
    "",
    "/** The operator's entire write surface: rerange, reduce, collect, exitAll, signal, pause. */",
    `export const OPERATOR_SELECTORS = ${literal(selectors)} as const;`,
    "",
    `export const OPERATOR_SIGNATURES = ${literal(signatures)} as const;`,
    "",
    "export type OperatorFunction = keyof typeof OPERATOR_SELECTORS;",
    "",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emits a TypeScript template-literal type into the generated module
    "export const OPERATOR_SELECTOR_SET: ReadonlySet<`0x${string}`> = new Set(Object.values(OPERATOR_SELECTORS));",
    "",
  ].join("\n");

  const deskLaneFactory = [
    header("IDeskLaneFactory.json", "factory"),
    `export const deskLaneFactoryAbi = ${literal(factory)} as const;`,
    "",
  ].join("\n");
  const priceFence = [
    header("IPriceFence.json", "fence"),
    `export const priceFenceAbi = ${literal(fenceAbi)} as const;`,
    "",
  ].join("\n");

  return {
    "DeskLane.ts": deskLane,
    "DeskLaneFactory.ts": deskLaneFactory,
    "PriceFence.ts": priceFence,
  };
}

function main(): void {
  const check = process.argv.includes("--check");
  const modules = renderModules();
  let stale = 0;
  for (const [file, content] of Object.entries(modules)) {
    const path = join(OUT_DIR, file);
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing */
    }
    if (current === content) continue;
    if (check) {
      console.error(`stale: ${path}`);
      stale += 1;
    } else {
      writeFileSync(path, content);
      console.log(`wrote ${path}`);
    }
  }
  if (check && stale > 0) {
    console.error("ABI modules are out of date: run `pnpm abi:sync`.");
    process.exit(1);
  }
  if (!check) console.log("abi-sync: up to date");
}

const isMain =
  typeof process.argv[1] === "string" && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
