/**
 * The calendar port must equal engine/markout/calendar.py on every golden case
 * (test/fixtures/calendar_cases.json, generated by engine/tests/gen_agent_fixtures.py).
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  civilFromDays,
  daysFromCivil,
  EARLY_CLOSES,
  etToEpochSec,
  HOLIDAYS,
  isoDateOfDays,
  isoWeekdayOfDays,
  isTradingDay,
  lastCompletedRegularSession,
  pythonWholeSecond,
  regimeAt,
  regularSessionBounds,
} from "../../src/market/calendar.js";

interface CalendarCase {
  ts: number;
  regime: string;
  reopen_kind: string | null;
  how: number;
  session_date: string;
}
const fixture = JSON.parse(
  readFileSync(new URL("../fixtures/calendar_cases.json", import.meta.url), "utf8"),
) as {
  holidays: string[];
  early_closes: string[];
  cases: CalendarCase[];
};

describe("calendar golden fixtures", () => {
  it("has the engine's holiday and early-close lists", () => {
    expect([...HOLIDAYS].sort()).toEqual([...fixture.holidays].sort());
    expect([...EARLY_CLOSES].sort()).toEqual([...fixture.early_closes].sort());
  });

  it(`matches every one of the ${fixture.cases.length} cases exactly`, () => {
    expect(fixture.cases.length).toBeGreaterThan(3000);
    const mismatches: string[] = [];
    for (const c of fixture.cases) {
      const r = regimeAt(c.ts);
      const got = {
        regime: r.name,
        reopen_kind: r.reopenKind,
        how: r.how,
        session_date: r.sessionDate,
      };
      const want = {
        regime: c.regime,
        reopen_kind: c.reopen_kind,
        how: c.how,
        session_date: c.session_date,
      };
      if (JSON.stringify(got) !== JSON.stringify(want)) {
        mismatches.push(`${c.ts}: got ${JSON.stringify(got)} want ${JSON.stringify(want)}`);
      }
    }
    expect(mismatches).toEqual([]);
  });

  it("covers every regime and both reopen kinds", () => {
    const regimes = new Set(fixture.cases.map((c) => c.regime));
    const kinds = new Set(fixture.cases.map((c) => c.reopen_kind));
    expect([...regimes].sort()).toEqual([
      "EXTENDED",
      "HOLIDAY",
      "OVERNIGHT",
      "REGULAR",
      "WEEKEND_DARK",
    ]);
    expect(kinds).toEqual(new Set([null, "weekday_open", "wake"]));
  });
});

describe("calendar semantics", () => {
  it("labels the evening before a holiday HOLIDAY (Labor Day 2026)", () => {
    // Sun Sep 6 2026 20:30 EDT = 00:30 UTC Sep 7
    const r = regimeAt(Date.UTC(2026, 8, 7, 0, 30) / 1000);
    expect(r.name).toBe("HOLIDAY");
    expect(r.sessionDate).toBe("2026-09-07");
  });

  it("recognises the weekday open guard and the Sunday wake", () => {
    // Mon Sep 21 2026 09:25 EDT = 13:25 UTC
    expect(regimeAt(Date.UTC(2026, 8, 21, 13, 25) / 1000).reopenKind).toBe("weekday_open");
    // Sun Sep 20 2026 20:05 EDT = 00:05 UTC Sep 21
    const wake = regimeAt(Date.UTC(2026, 8, 21, 0, 5) / 1000);
    expect(wake.reopenKind).toBe("wake");
    expect(wake.name).toBe("OVERNIGHT");
  });

  it("uses the 13:00 early close", () => {
    // Fri Nov 27 2026 13:30 EST = 18:30 UTC
    expect(regimeAt(Date.UTC(2026, 10, 27, 18, 30) / 1000).name).toBe("EXTENDED");
    expect(regimeAt(Date.UTC(2026, 10, 27, 17, 30) / 1000).name).toBe("REGULAR");
  });

  it("rounds fractional seconds like Python (half-even to microseconds, carry into the next second)", () => {
    expect(pythonWholeSecond(100.4)).toBe(100);
    expect(pythonWholeSecond(100.9999994)).toBe(100);
    expect(pythonWholeSecond(100.9999996)).toBe(101);
    // 13:59:59.9999996 UTC is 14:00:00 for Python
    const t = Date.UTC(2026, 8, 21, 13, 59, 59) / 1000 + 0.9999996;
    expect(regimeAt(t).et.minute).toBe(0);
  });
});

describe("civil dates", () => {
  it("round-trips day numbers and weekdays", () => {
    for (let d = -800_000; d <= 800_000; d += 997) {
      const c = civilFromDays(d);
      expect(daysFromCivil(c.year, c.month, c.day)).toBe(d);
    }
    expect(isoDateOfDays(0)).toBe("1970-01-01");
    expect(isoWeekdayOfDays(0)).toBe(4); // Thursday
    expect(isoWeekdayOfDays(daysFromCivil(2026, 9, 19))).toBe(6); // Saturday
    expect(isTradingDay(daysFromCivil(2026, 9, 7))).toBe(false); // Labor Day
    expect(isTradingDay(daysFromCivil(2026, 9, 21))).toBe(true);
  });

  it("converts ET wall clock to epoch across both DST states", () => {
    expect(etToEpochSec(2026, 9, 21, 9, 30)).toBe(Date.UTC(2026, 8, 21, 13, 30) / 1000); // EDT
    expect(etToEpochSec(2026, 12, 21, 9, 30)).toBe(Date.UTC(2026, 11, 21, 14, 30) / 1000); // EST
    expect(etToEpochSec(2026, 3, 9, 9, 30)).toBe(Date.UTC(2026, 2, 9, 13, 30) / 1000); // day after spring forward
  });

  it("finds regular session bounds and the last completed session", () => {
    const b = regularSessionBounds("2026-11-27");
    expect(b.endSec - b.startSec).toBe(3.5 * 3600);
    // Mon Sep 21 2026 10:00 ET: the last completed regular session is Fri Sep 18
    expect(lastCompletedRegularSession(Date.UTC(2026, 8, 21, 14, 0) / 1000)).toBe("2026-09-18");
    // Tue Sep 8 2026 17:00 ET: Tuesday itself has closed (Monday was Labor Day)
    expect(lastCompletedRegularSession(Date.UTC(2026, 8, 8, 21, 0) / 1000)).toBe("2026-09-08");
    // Tue Sep 8 2026 09:00 ET: skips the Labor Day holiday back to Fri Sep 4
    expect(lastCompletedRegularSession(Date.UTC(2026, 8, 8, 13, 0) / 1000)).toBe("2026-09-04");
  });
});
