// GENERATED by web/scripts/brand/generate.mjs. Do not edit: change geometry.ts or the generator and re-run it.
// Path data for <DeltaMark> (the compact seal and the bare 3-stroke Δ).

export const MARK_SEAL_VIEWBOX = 40;
export const MARK_SEAL_RING: string = "M0.9 20A19.1 19.1 0 1 0 39.1 20A19.1 19.1 0 1 0 0.9 20Z";
export const MARK_SEAL_RING_INNER: string = "M2.7 20A17.3 17.3 0 1 0 37.3 20A17.3 17.3 0 1 0 2.7 20Z";
export const MARK_SEAL_DELTA: string[] = ["M20 8.6L9.4 27.6L30.6 27.6Z","M18.655 11.012L10.544 25.55L26.765 25.55Z","M17.309 13.423L11.687 23.5L22.931 23.5Z"];
export const MARK_DELTA_VIEWBOX = 32;
export const MARK_DELTA: string[] = ["M16 4.2L3.2 27.2L28.8 27.2Z","M14.341 7.182L4.591 24.7L24.09 24.7Z","M12.681 10.164L5.983 22.2L19.38 22.2Z"];
export const MARK_FAVICON: string = "M16 3.6L3.2 27.4L28.8 27.4ZM14.24 10.884L7.616 23.2L20.864 23.2Z";
